### ISSUE TITLE
The Quatar livery

### ISSUE THREAD

**Issue by BlooketHackerx** [Ariakim-Taiyo/LiveryChanger#1]
Every time I click "Quatar" in the CC aircraft it makes my computer crash. My whole computer just goes black and restarts. Is this because the livery is hard to load in or what because I have had ZERO trouble with loading all the other liveries. What are your thoughts

**Comment by Ariakim-Taiyo** [comment]
Due to the nature of the texture resolution of the A350K, it is very hard to load. i dont know why Nightshade decided to use 8k textures on his aircraft when even 2k would have been sufficient.

**Comment by BlooketHackerx** [comment]
oof. Also is the 707 coming out? or was that canceled because I watched the trailer and it looks awesome.

**Comment by Ariakim-Taiyo** [comment]
it is being reworked
