### ISSUE TITLE
looks like there was a livery mix up

### ISSUE THREAD

**Issue by abinofcake** [Ariakim-Taiyo/LiveryChanger#10]
![image](https://user-images.githubusercontent.com/99083788/155253445-751e2ba4-707a-47ce-a01c-368d79f22a6b.png)
![image](https://user-images.githubusercontent.com/99083788/155253514-414b913c-b642-45eb-8834-ecfac5c8d2b2.png)

**Comment by Ariakim-Taiyo** [comment]
Lol LRX tried this again. i should have it patched by the end of the day.

**Comment by Ariakim-Taiyo** [comment]
Alright, i patched the issue.
