### ISSUE TITLE
LRX back at it again!

### ISSUE THREAD

**Issue by abinofcake** [Ariakim-Taiyo/LiveryChanger#12]
![image](https://user-images.githubusercontent.com/99083788/155643459-ace60974-e0cd-4790-91cc-ecfd57069917.png)
![image](https://user-images.githubusercontent.com/99083788/155643587-6223182d-5da9-4b0d-b1ea-a16a50e8e17c.png)

**Comment by thinkgeofsgame** [comment]
thats looks even worse than normal livery

**Comment by thinkgeofsgame** [comment]
![image](https://user-images.githubusercontent.com/99663982/155715028-062d2d5d-4ce0-4c13-87b0-d860e558382c.png)

**Comment by thinkgeofsgame** [comment]
but A321 its look kinda normal :
![image](https://user-images.githubusercontent.com/99663982/155715290-365ecafd-3468-4d23-8884-f6c8a60d8971.png)

**Comment by thinkgeofsgame** [comment]
in geo-fs 2.9 :
![image](https://user-images.githubusercontent.com/99663982/155717051-af66df87-566f-44a8-bdf5-411bf697c873.png)

**Comment by thinkgeofsgame** [comment]
you need to use 3.0 beta because @Ariakim-Taiyo is looking for into it

**Comment by thinkgeofsgame** [comment]
use geofs 3.0

**Comment by Ariakim-Taiyo** [comment]
Fixed. The bookmark script is slightly wonky still, so it takes a few tries for the liveries to align properly.
