### ISSUE TITLE
Hi, the qatar a350, air canada 737 700, lufthansa 747 and united a321 neo liveries are somehow broken

### ISSUE THREAD

**Issue by YUSHENGAIRPLANE** [Ariakim-Taiyo/LiveryChanger#16]
Hi, the qatar a350, air canada 737 700, lufthansa 747 and united a321 neo liveries are somehow broken

**Comment by thinkgeofsgame** [comment]
![image](https://user-images.githubusercontent.com/99663982/158124846-21da015c-03fa-45ab-b68f-dec55e3831ed.png)

**Comment by thinkgeofsgame** [comment]
![image](https://user-images.githubusercontent.com/99663982/158124971-cb186b12-069d-4cd0-8bd7-d3d045aed899.png)

**Comment by thinkgeofsgame** [comment]
![image](https://user-images.githubusercontent.com/99663982/158125313-d9ec2904-90fb-4db0-a1ad-8eaaf85b250d.png)

**Comment by thinkgeofsgame** [comment]
got this error when pasting the code
