### ISSUE TITLE
Would it be possible to get a U.S airways livery for the a320-214? 

### ISSUE THREAD

**Issue by BlooketHackerx** [Ariakim-Taiyo/LiveryChanger#2]
I tried to understand how to make a new livery but I am bad at coding so can u help me make one or maybe even make one urself? I know it is stupid and a lot to ask so please don't take it as me begging u to make something because it's not and if u can't that is fine just wondering because it would be a cool livery to fly with.

**Comment by BlooketHackerx** [comment]
Maybe?

**Comment by Ariakim-Taiyo** [comment]
Possibly, but this project is on hold for a bit while I work on the 737-200 for geofs.

**Comment by BlooketHackerx** [comment]
Woah 737-200? I can't wait for that!!

**Comment by BlooketHackerx** [comment]
Thanks for all you do!
