### ISSUE TITLE
LIVERIES

### ISSUE THREAD

**Issue by GoogleWasAllMyIdea** [Ariakim-Taiyo/LiveryChanger#21]
So like, the new liveries work but um... this happens.
![Screenshot 2022-03-23 1 32 34 PM](https://user-images.githubusercontent.com/95721628/159760771-04106211-5edf-46e0-8a0e-20942d00ca8c.png)

**Comment by BlooketHackerx** [comment]
the liveries are broken and textures are where they should not be.

**Comment by Ariakim-Taiyo** [comment]
THe new liveries are not developed or maintained by me. You will have to contact their respective developers to get more information about when they will be fixed.

**Comment by Bassemtellawi** [comment]
Niceeee please add Turkish Airlines 737-800 and A350, Egypt Air 737-800 and 787-9 , Middle East Airlines A320, fly Dubai 737-800 , pegasus airlines 737-800 . Does the added liveries work on Android? Thank you 🙏

**Comment by Bassemtellawi** [comment]
Niceeee does those liveries work on Android?🙏

**Comment by Ariakim-Taiyo** [comment]
@Bassemtellawi The liveries are only compatible with the web browser based GeoFs. If you can use a console on android then it might work in the browser.

**Comment by Bassemtellawi** [comment]
Thank you so much 🙏 will try to to add console for Android. Please as well if you could add to game Turkish Airlines B737-800 and A350-900, Egypt Air B737-800 and B787-9, Middle East Airlines A320, A330-200, A321neo , Pegasus Airlines A320neo and Fly Dubai B737-800, B737max . Thank you 🙏

**Comment by githubuser589** [comment]
> Thank you so much 🙏 will try to to add console for Android. Please as well if you could add to game Turkish Airlines B737-800 and A350-900, Egypt Air B737-800 and B787-9, Middle East Airlines A320, A330-200, A321neo , Pegasus Airlines A320neo and Fly Dubai B737-800, B737max . Thank you 🙏

there's not even an a330-200 lol
