### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by iuhairways** [Ariakim-Taiyo/LiveryChanger#23]
Look at A321neo
![Screenshot 2022-04-05 6 14 18 PM](https://user-images.githubusercontent.com/103064103/161813782-9d8c6381-db93-4ad3-a99d-b14bb0ec24ca.png)
 Also 747-800
![Screenshot 2022-04-05 6 15 33 PM](https://user-images.githubusercontent.com/103064103/161813863-19196caa-3f9a-46f6-9b68-a71528e95e18.png)
 They were ok before you added the new 737 liveries

**Comment by iuhairways** [comment]
737 transavia, ethopian and china east are also broken

**Comment by iuhairways** [comment]
> Look at A321neo ![Screenshot 2022-04-05 6 14 18 PM](https://user-images.githubusercontent.com/103064103/161813782-9d8c6381-db93-4ad3-a99d-b14bb0ec24ca.png) Also 747-800 ![Screenshot 2022-04-05 6 15 33 PM](https://user-images.githubusercontent.com/103064103/161813863-19196caa-3f9a-46f6-9b68-a71528e95e18.png) They were ok before you added the new 737 liveries

but these ones?

**Comment by abinofcake** [comment]
> but these ones?

I'm guessing they will be fixed sometime later

**Comment by iuhairways** [comment]
> > but these ones?
> 
> I'm guessing they will be fixed sometime later

why not NOW

**Comment by abinofcake** [comment]
> > > but these ones?
> > 
> > 
> > I'm guessing they will be fixed sometime later
> 
> why not NOW

It takes time to fix something, be patient. Ariakim has to come up with a fix, but it will take some time; it doesn't just take 10 seconds.

**Comment by iuhairways** [comment]
ok

**Comment by iuhairways** [comment]
but they benn ages

**Comment by abinofcake** [comment]
> but they benn ages

It hasn't even been a week..
