### ISSUE TITLE
Lufthansa 747

### ISSUE THREAD

**Issue by thedolphinsfan1** [Ariakim-Taiyo/LiveryChanger#27]
The 747 has parts of the livery scattered all over it. I don't know if this is a common problem.

**Comment by thedolphinsfan1** [comment]
![Screenshot 2022-08-16 3 16 50 PM](https://user-images.githubusercontent.com/111387425/184963568-40420d27-a449-483d-913f-34310d2c095f.png)

This is the problem:

**Comment by githubuser589** [comment]
This project isn’t being updated anymore so I don’t really think there’s a point to reporting problems anymore lol

**Comment by thedolphinsfan1** [comment]
ok thanks
