### ISSUE TITLE
United A321neo livery

### ISSUE THREAD

**Issue by abinofcake** [Ariakim-Taiyo/LiveryChanger#5]
After loading in the new United A321, I am presented with this...
![Screenshot 2022-02-16 11 20 01 AM](https://user-images.githubusercontent.com/99083788/154317417-907b8031-9c58-45f9-86f5-797c1c7b6790.png)

**Comment by thinkgeofsgame** [comment]
i also get that livery tho i think its mis placed

**Comment by thinkgeofsgame** [comment]
now its working fine :

![image](https://user-images.githubusercontent.com/99663982/154458202-896d2135-258a-457f-9e54-67324eb22a8a.png)

**Comment by abinofcake** [comment]
thanks

**Comment by Ariakim-Taiyo** [comment]
Should work in both 2.9 and 3.01, but i will look into it.
