### ISSUE TITLE
Lufthansa 747-8 livery

### ISSUE THREAD

**Issue by abinofcake** [Ariakim-Taiyo/LiveryChanger#7]
Hello, whenever I try to load in the Lufthansa livery for the LRX 747-8, it does not work. I am running GeoFS on version 2.9 and I have already tried loading in the base aircraft before the liveries, but this does not work. Is there any workaround to this?

**Comment by thinkgeofsgame** [comment]
but on mine its all misplaced and when i take a screenshot my whole pc crashes so i cannot take a screenshot.
i think @Ariakim-Taiyo will fix this too.

**Comment by Ariakim-Taiyo** [comment]
@abinofcake Do you have access to the console or are you using the bookmark? if you can access the console then please share a creenshot of it.

**Comment by Ariakim-Taiyo** [comment]
Is this after you clicked on the 747 livery? It looks like this was just after you executed the code. try clicking on the 747 livery and then sending me the console output.

**Comment by abinofcake** [comment]
clicked the 747 livery,
![image](https://user-images.githubusercontent.com/99083788/155155879-206d835a-dd64-455e-9b13-4971038de349.png)

**Comment by Ariakim-Taiyo** [comment]
Hmm, looks like there might have been an update to the 747, i need to reroute the model index and find the new texture base. I just realized that LRX may have intentionally broken all my liveries on 2.9. I will look into fixing it asap.

**Comment by Ariakim-Taiyo** [comment]
I just patched the 747, but the a321 is still broken atm. i will fix it soon.

**Comment by Ariakim-Taiyo** [comment]
And the A321 is back up.
